import express from "express";
import cors from "cors";
import nodemailer from "nodemailer";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { JSDOM } from "jsdom";

const app = express();
app.use(cors());
app.use(express.json({ limit: "10mb" }));

app.post("/send-pdf", async (req, res) => {
  const { email, chatHtml } = req.body;

  try {
    const dom = new JSDOM(chatHtml);
    const body = dom.window.document.body;
    const rawText = body ? body.textContent : "";
    const text = typeof rawText === "string" ? rawText.trim() : "";

    const pdfDoc = await PDFDocument.create();

    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    const colors = {
      blue: rgb(0, 120/255, 255/255),
      yellow: rgb(1, 212/255, 59/255),
      gray: rgb(68/255, 68/255, 68/255),
      white: rgb(1, 1, 1)
    };

    // -----------------------------
    // COVER PAGE
    // -----------------------------
    const cover = pdfDoc.addPage([612, 792]);
    const { width, height } = cover.getSize();

    cover.drawRectangle({
      x: 0,
      y: height - 180,
      width,
      height: 180,
      color: colors.blue
    });

    cover.drawText("Leave of Absence Law Finder", {
      x: 50,
      y: height - 240,
      size: 28,
      font: fontBold,
      color: colors.gray
    });

    cover.drawText("Your Personalized Leave Summary", {
      x: 50,
      y: height - 280,
      size: 18,
      font,
      color: colors.gray
    });

    cover.drawText(`Generated for: ${email}`, {
      x: 50,
      y: height - 320,
      size: 12,
      font,
      color: colors.gray
    });

    cover.drawText(`Date: ${new Date().toLocaleDateString()}`, {
      x: 50,
      y: height - 340,
      size: 12,
      font,
      color: colors.gray
    });

    // -----------------------------
    // HELPERS
    // -----------------------------
    function addPageNumber(page, number) {
      page.drawText(`Page ${number}`, {
        x: 520,
        y: 20,
        size: 10,
        font,
        color: colors.gray
      });
    }

    function addFooter(page) {
      page.drawText("Generated by Leave of Absence Law Finder", {
        x: 50,
        y: 20,
        size: 10,
        font,
        color: colors.gray
      });

      page.drawText("Confidential — For personal use only", {
        x: 50,
        y: 8,
        size: 8,
        font,
        color: colors.gray
      });
    }

    function drawWrappedText(page, text, x, y, font, fontSize, maxWidth, lineHeight) {
        if (!text || typeof text !== "string") {
    return y;

      const words = text.split(" ");
      let line = "";

      for (let word of words) {
        const testLine = line + word + " ";
        const testWidth = font.widthOfTextAtSize(testLine, fontSize);

        if (testWidth > maxWidth) {
          page.drawText(line, { x, y, size: fontSize, font, color: colors.gray });
          line = word + " ";
          y -= lineHeight;
        } else {
          line = testLine;
        }
      }

      if (line.trim()) {
        page.drawText(line, { x, y, size: fontSize, font, color: colors.gray });
      }

      return y - lineHeight;
    }

    // -----------------------------
    // CONTENT PAGES
    // -----------------------------
    let page = pdfDoc.addPage([612, 792]);
    let y = 740;
    let pageNumber = 2;

    addPageNumber(page, pageNumber);
    addFooter(page);

    // Section Title
    page.drawText("Summary of Applicable Leave Laws", {
      x: 50,
      y,
      size: 16,
      font: fontBold,
      color: colors.blue
    });
    y -= 30;

    // Draw wrapped text
    y = drawWrappedText(
      page,
      text,
      50,
      y,
      font,
      12,
      512,
      16
    );

    // Add new pages as needed
    while (y < 80) {
      page = pdfDoc.addPage([612, 792]);
      pageNumber++;
      addPageNumber(page, pageNumber);
      addFooter(page);
      y = 740;
    }

    const pdfBytes = await pdfDoc.save();

    // -----------------------------
    // EMAIL
    // -----------------------------
    const transporter = nodemailer.createTransport({
      service: "gmail",
      auth: {
        user: "twebb2590@gmail.com",
        pass: "izte pzbk xqph kmth"
      }
    });

    await transporter.sendMail({
      from: "twebb2590@gmail.com",
      to: email,
      subject: "Your Leave Summary PDF",
      text: "Attached is your personalized leave summary.",
      attachments: [
        {
          filename: "leave-summary.pdf",
          content: pdfBytes
        }
      ]
    });

    res.status(200).json({ success: true });

  } catch (err) {
    console.error("PDF/email error:", err);
    res.status(500).json({ error: "Failed to send PDF" });
  }
});

// Required for Render
app.get("/", (req, res) => {
  res.send("PDF service is running");
});

app.listen(3000, () => console.log("Server running on port 3000"));
